export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  TIMEOUT: 'TIMEOUT',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',

  // Integrations
  PETPOOJA_UPSTREAM: 'PETPOOJA_UPSTREAM',
  PETPOOJA_WEBHOOK_INVALID: 'PETPOOJA_WEBHOOK_INVALID',
  RAZORPAY_UPSTREAM: 'RAZORPAY_UPSTREAM',
  RAZORPAY_SIGNATURE_INVALID: 'RAZORPAY_SIGNATURE_INVALID',
  FCM_UPSTREAM: 'FCM_UPSTREAM',

  // Domain
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
