/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForceUpdateRouteImport } from './routes/force-update'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileFavoritesRouteImport } from './routes/profile.favorites'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AddressesCreateRouteImport } from './routes/addresses.create'
import { Route as OrdersOrderIdIndexRouteImport } from './routes/orders.$orderId.index'
import { Route as OrdersOrderIdTrackRouteImport } from './routes/orders.$orderId.track'
import { Route as MenuProductProductIdRouteImport } from './routes/menu.product.$productId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForceUpdateRoute = ForceUpdateRouteImport.update({
  id: '/force-update',
  path: '/force-update',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFavoritesRoute = ProfileFavoritesRouteImport.update({
  id: '/profile/favorites',
  path: '/profile/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesCreateRoute = AddressesCreateRouteImport.update({
  id: '/addresses/create',
  path: '/addresses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdIndexRoute = OrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdTrackRoute = OrdersOrderIdTrackRouteImport.update({
  id: '/orders/$orderId/track',
  path: '/orders/$orderId/track',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuProductProductIdRoute = MenuProductProductIdRouteImport.update({
  id: '/menu/product/$productId',
  path: '/menu/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/force-update': typeof ForceUpdateRoute
  '/home': typeof HomeRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/addresses/create': typeof AddressesCreateRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/orders/$orderId/': typeof OrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/force-update': typeof ForceUpdateRoute
  '/home': typeof HomeRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/addresses/create': typeof AddressesCreateRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/menu': typeof MenuIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/orders/$orderId': typeof OrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/force-update': typeof ForceUpdateRoute
  '/home': typeof HomeRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/addresses/create': typeof AddressesCreateRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/orders/$orderId/': typeof OrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/force-update'
    | '/home'
    | '/maintenance'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/search'
    | '/stores'
    | '/support'
    | '/terms'
    | '/addresses/create'
    | '/auth/login'
    | '/auth/otp'
    | '/order-confirmation/$orderId'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/notifications'
    | '/profile/settings'
    | '/menu/'
    | '/orders/'
    | '/profile/'
    | '/menu/product/$productId'
    | '/orders/$orderId/track'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/force-update'
    | '/home'
    | '/maintenance'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/search'
    | '/stores'
    | '/support'
    | '/terms'
    | '/addresses/create'
    | '/auth/login'
    | '/auth/otp'
    | '/order-confirmation/$orderId'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/notifications'
    | '/profile/settings'
    | '/menu'
    | '/orders'
    | '/profile'
    | '/menu/product/$productId'
    | '/orders/$orderId/track'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/force-update'
    | '/home'
    | '/maintenance'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/search'
    | '/stores'
    | '/support'
    | '/terms'
    | '/addresses/create'
    | '/auth/login'
    | '/auth/otp'
    | '/order-confirmation/$orderId'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/notifications'
    | '/profile/settings'
    | '/menu/'
    | '/orders/'
    | '/profile/'
    | '/menu/product/$productId'
    | '/orders/$orderId/track'
    | '/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForceUpdateRoute: typeof ForceUpdateRoute
  HomeRoute: typeof HomeRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OffersRoute: typeof OffersRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  StoresRoute: typeof StoresRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AddressesCreateRoute: typeof AddressesCreateRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileFavoritesRoute: typeof ProfileFavoritesRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  MenuIndexRoute: typeof MenuIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  MenuProductProductIdRoute: typeof MenuProductProductIdRoute
  OrdersOrderIdTrackRoute: typeof OrdersOrderIdTrackRoute
  OrdersOrderIdIndexRoute: typeof OrdersOrderIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-update': {
      id: '/force-update'
      path: '/force-update'
      fullPath: '/force-update'
      preLoaderRoute: typeof ForceUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/favorites': {
      id: '/profile/favorites'
      path: '/profile/favorites'
      fullPath: '/profile/favorites'
      preLoaderRoute: typeof ProfileFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses/create': {
      id: '/addresses/create'
      path: '/addresses/create'
      fullPath: '/addresses/create'
      preLoaderRoute: typeof AddressesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId/': {
      id: '/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof OrdersOrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId/track': {
      id: '/orders/$orderId/track'
      path: '/orders/$orderId/track'
      fullPath: '/orders/$orderId/track'
      preLoaderRoute: typeof OrdersOrderIdTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/product/$productId': {
      id: '/menu/product/$productId'
      path: '/menu/product/$productId'
      fullPath: '/menu/product/$productId'
      preLoaderRoute: typeof MenuProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForceUpdateRoute: ForceUpdateRoute,
  HomeRoute: HomeRoute,
  MaintenanceRoute: MaintenanceRoute,
  OffersRoute: OffersRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  StoresRoute: StoresRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AddressesCreateRoute: AddressesCreateRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileFavoritesRoute: ProfileFavoritesRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  MenuIndexRoute: MenuIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  MenuProductProductIdRoute: MenuProductProductIdRoute,
  OrdersOrderIdTrackRoute: OrdersOrderIdTrackRoute,
  OrdersOrderIdIndexRoute: OrdersOrderIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
