/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForceUpdateRouteImport } from './routes/force-update'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileFavoritesRouteImport } from './routes/profile.favorites'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSegmentsRouteImport } from './routes/admin.segments'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPetpoojaRouteImport } from './routes/admin.petpooja'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPaymentHealthRouteImport } from './routes/admin.payment-health'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDeveloperRouteImport } from './routes/admin.developer'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminAutomationRouteImport } from './routes/admin.automation'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AddressesCreateRouteImport } from './routes/addresses.create'
import { Route as OrdersOrderIdIndexRouteImport } from './routes/orders.$orderId.index'
import { Route as AdminSystemIndexRouteImport } from './routes/admin.system.index'
import { Route as AdminPetpoojaIndexRouteImport } from './routes/admin.petpooja.index'
import { Route as OrdersOrderIdTrackRouteImport } from './routes/orders.$orderId.track'
import { Route as MenuProductProductIdRouteImport } from './routes/menu.product.$productId'
import { Route as AdminSystemSettingsRouteImport } from './routes/admin.system.settings'
import { Route as AdminSystemSecurityRouteImport } from './routes/admin.system.security'
import { Route as AdminSystemRedisRouteImport } from './routes/admin.system.redis'
import { Route as AdminSystemQueuesRouteImport } from './routes/admin.system.queues'
import { Route as AdminSystemMetricsRouteImport } from './routes/admin.system.metrics'
import { Route as AdminSystemLogsRouteImport } from './routes/admin.system.logs'
import { Route as AdminSystemJobsRouteImport } from './routes/admin.system.jobs'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system.health'
import { Route as AdminSystemFeatureFlagsRouteImport } from './routes/admin.system.feature-flags'
import { Route as AdminSystemDatabaseRouteImport } from './routes/admin.system.database'
import { Route as AdminSystemAuditRouteImport } from './routes/admin.system.audit'
import { Route as AdminSystemApisRouteImport } from './routes/admin.system.apis'
import { Route as AdminStoresCreateRouteImport } from './routes/admin.stores.create'
import { Route as AdminStoresStoreIdRouteImport } from './routes/admin.stores.$storeId'
import { Route as AdminPetpoojaWebhooksRouteImport } from './routes/admin.petpooja.webhooks'
import { Route as AdminPetpoojaStoresRouteImport } from './routes/admin.petpooja.stores'
import { Route as AdminPetpoojaQueuesRouteImport } from './routes/admin.petpooja.queues'
import { Route as AdminPetpoojaLogsRouteImport } from './routes/admin.petpooja.logs'
import { Route as AdminPetpoojaHealthRouteImport } from './routes/admin.petpooja.health'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin.payments.$id'
import { Route as AdminOrdersLiveRouteImport } from './routes/admin.orders.live'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminCustomersSegmentsRouteImport } from './routes/admin.customers.segments'
import { Route as AdminCustomersLoyaltyRouteImport } from './routes/admin.customers.loyalty'
import { Route as AdminCustomersAnalyticsRouteImport } from './routes/admin.customers.analytics'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminCampaignsCreateRouteImport } from './routes/admin.campaigns.create'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForceUpdateRoute = ForceUpdateRouteImport.update({
  id: '/force-update',
  path: '/force-update',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFavoritesRoute = ProfileFavoritesRouteImport.update({
  id: '/profile/favorites',
  path: '/profile/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentsRoute = AdminSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPetpoojaRoute = AdminPetpoojaRouteImport.update({
  id: '/petpooja',
  path: '/petpooja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentHealthRoute = AdminPaymentHealthRouteImport.update({
  id: '/payment-health',
  path: '/payment-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeveloperRoute = AdminDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AddressesCreateRoute = AddressesCreateRouteImport.update({
  id: '/addresses/create',
  path: '/addresses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdIndexRoute = OrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemIndexRoute = AdminSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminPetpoojaIndexRoute = AdminPetpoojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPetpoojaRoute,
} as any)
const OrdersOrderIdTrackRoute = OrdersOrderIdTrackRouteImport.update({
  id: '/orders/$orderId/track',
  path: '/orders/$orderId/track',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuProductProductIdRoute = MenuProductProductIdRouteImport.update({
  id: '/menu/product/$productId',
  path: '/menu/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemSecurityRoute = AdminSystemSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemRedisRoute = AdminSystemRedisRouteImport.update({
  id: '/redis',
  path: '/redis',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemQueuesRoute = AdminSystemQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemMetricsRoute = AdminSystemMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemLogsRoute = AdminSystemLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemJobsRoute = AdminSystemJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemFeatureFlagsRoute = AdminSystemFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemDatabaseRoute = AdminSystemDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemAuditRoute = AdminSystemAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminSystemApisRoute = AdminSystemApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AdminSystemRoute,
} as any)
const AdminStoresCreateRoute = AdminStoresCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminStoresRoute,
} as any)
const AdminStoresStoreIdRoute = AdminStoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AdminStoresRoute,
} as any)
const AdminPetpoojaWebhooksRoute = AdminPetpoojaWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminPetpoojaRoute,
} as any)
const AdminPetpoojaStoresRoute = AdminPetpoojaStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminPetpoojaRoute,
} as any)
const AdminPetpoojaQueuesRoute = AdminPetpoojaQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AdminPetpoojaRoute,
} as any)
const AdminPetpoojaLogsRoute = AdminPetpoojaLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminPetpoojaRoute,
} as any)
const AdminPetpoojaHealthRoute = AdminPetpoojaHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminPetpoojaRoute,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminOrdersLiveRoute = AdminOrdersLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminCustomersSegmentsRoute = AdminCustomersSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersLoyaltyRoute = AdminCustomersLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersAnalyticsRoute = AdminCustomersAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCampaignsCreateRoute = AdminCampaignsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/force-update': typeof ForceUpdateRoute
  '/home': typeof HomeRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/addresses/create': typeof AddressesCreateRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/campaigns': typeof AdminCampaignsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/developer': typeof AdminDeveloperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-health': typeof AdminPaymentHealthRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/petpooja': typeof AdminPetpoojaRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/system': typeof AdminSystemRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/campaigns/create': typeof AdminCampaignsCreateRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/analytics': typeof AdminCustomersAnalyticsRoute
  '/admin/customers/loyalty': typeof AdminCustomersLoyaltyRoute
  '/admin/customers/segments': typeof AdminCustomersSegmentsRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/live': typeof AdminOrdersLiveRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/petpooja/health': typeof AdminPetpoojaHealthRoute
  '/admin/petpooja/logs': typeof AdminPetpoojaLogsRoute
  '/admin/petpooja/queues': typeof AdminPetpoojaQueuesRoute
  '/admin/petpooja/stores': typeof AdminPetpoojaStoresRoute
  '/admin/petpooja/webhooks': typeof AdminPetpoojaWebhooksRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/admin/stores/create': typeof AdminStoresCreateRoute
  '/admin/system/apis': typeof AdminSystemApisRoute
  '/admin/system/audit': typeof AdminSystemAuditRoute
  '/admin/system/database': typeof AdminSystemDatabaseRoute
  '/admin/system/feature-flags': typeof AdminSystemFeatureFlagsRoute
  '/admin/system/health': typeof AdminSystemHealthRoute
  '/admin/system/jobs': typeof AdminSystemJobsRoute
  '/admin/system/logs': typeof AdminSystemLogsRoute
  '/admin/system/metrics': typeof AdminSystemMetricsRoute
  '/admin/system/queues': typeof AdminSystemQueuesRoute
  '/admin/system/redis': typeof AdminSystemRedisRoute
  '/admin/system/security': typeof AdminSystemSecurityRoute
  '/admin/system/settings': typeof AdminSystemSettingsRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/admin/petpooja/': typeof AdminPetpoojaIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/orders/$orderId/': typeof OrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/force-update': typeof ForceUpdateRoute
  '/home': typeof HomeRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/addresses/create': typeof AddressesCreateRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/campaigns': typeof AdminCampaignsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/developer': typeof AdminDeveloperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-health': typeof AdminPaymentHealthRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/menu': typeof MenuIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/campaigns/create': typeof AdminCampaignsCreateRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/analytics': typeof AdminCustomersAnalyticsRoute
  '/admin/customers/loyalty': typeof AdminCustomersLoyaltyRoute
  '/admin/customers/segments': typeof AdminCustomersSegmentsRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/live': typeof AdminOrdersLiveRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/petpooja/health': typeof AdminPetpoojaHealthRoute
  '/admin/petpooja/logs': typeof AdminPetpoojaLogsRoute
  '/admin/petpooja/queues': typeof AdminPetpoojaQueuesRoute
  '/admin/petpooja/stores': typeof AdminPetpoojaStoresRoute
  '/admin/petpooja/webhooks': typeof AdminPetpoojaWebhooksRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/admin/stores/create': typeof AdminStoresCreateRoute
  '/admin/system/apis': typeof AdminSystemApisRoute
  '/admin/system/audit': typeof AdminSystemAuditRoute
  '/admin/system/database': typeof AdminSystemDatabaseRoute
  '/admin/system/feature-flags': typeof AdminSystemFeatureFlagsRoute
  '/admin/system/health': typeof AdminSystemHealthRoute
  '/admin/system/jobs': typeof AdminSystemJobsRoute
  '/admin/system/logs': typeof AdminSystemLogsRoute
  '/admin/system/metrics': typeof AdminSystemMetricsRoute
  '/admin/system/queues': typeof AdminSystemQueuesRoute
  '/admin/system/redis': typeof AdminSystemRedisRoute
  '/admin/system/security': typeof AdminSystemSecurityRoute
  '/admin/system/settings': typeof AdminSystemSettingsRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/admin/petpooja': typeof AdminPetpoojaIndexRoute
  '/admin/system': typeof AdminSystemIndexRoute
  '/orders/$orderId': typeof OrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/force-update': typeof ForceUpdateRoute
  '/home': typeof HomeRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/addresses/create': typeof AddressesCreateRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/campaigns': typeof AdminCampaignsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/developer': typeof AdminDeveloperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-health': typeof AdminPaymentHealthRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/petpooja': typeof AdminPetpoojaRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/system': typeof AdminSystemRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/campaigns/create': typeof AdminCampaignsCreateRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customers/analytics': typeof AdminCustomersAnalyticsRoute
  '/admin/customers/loyalty': typeof AdminCustomersLoyaltyRoute
  '/admin/customers/segments': typeof AdminCustomersSegmentsRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/live': typeof AdminOrdersLiveRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/petpooja/health': typeof AdminPetpoojaHealthRoute
  '/admin/petpooja/logs': typeof AdminPetpoojaLogsRoute
  '/admin/petpooja/queues': typeof AdminPetpoojaQueuesRoute
  '/admin/petpooja/stores': typeof AdminPetpoojaStoresRoute
  '/admin/petpooja/webhooks': typeof AdminPetpoojaWebhooksRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/admin/stores/create': typeof AdminStoresCreateRoute
  '/admin/system/apis': typeof AdminSystemApisRoute
  '/admin/system/audit': typeof AdminSystemAuditRoute
  '/admin/system/database': typeof AdminSystemDatabaseRoute
  '/admin/system/feature-flags': typeof AdminSystemFeatureFlagsRoute
  '/admin/system/health': typeof AdminSystemHealthRoute
  '/admin/system/jobs': typeof AdminSystemJobsRoute
  '/admin/system/logs': typeof AdminSystemLogsRoute
  '/admin/system/metrics': typeof AdminSystemMetricsRoute
  '/admin/system/queues': typeof AdminSystemQueuesRoute
  '/admin/system/redis': typeof AdminSystemRedisRoute
  '/admin/system/security': typeof AdminSystemSecurityRoute
  '/admin/system/settings': typeof AdminSystemSettingsRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/admin/petpooja/': typeof AdminPetpoojaIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/orders/$orderId/': typeof OrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/force-update'
    | '/home'
    | '/maintenance'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/search'
    | '/stores'
    | '/support'
    | '/terms'
    | '/addresses/create'
    | '/admin/analytics'
    | '/admin/automation'
    | '/admin/campaigns'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/developer'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payment-health'
    | '/admin/payments'
    | '/admin/petpooja'
    | '/admin/profile'
    | '/admin/reconciliation'
    | '/admin/refunds'
    | '/admin/segments'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/system'
    | '/admin/templates'
    | '/auth/login'
    | '/auth/otp'
    | '/order-confirmation/$orderId'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/notifications'
    | '/profile/settings'
    | '/admin/'
    | '/menu/'
    | '/orders/'
    | '/profile/'
    | '/admin/campaigns/create'
    | '/admin/customers/$id'
    | '/admin/customers/analytics'
    | '/admin/customers/loyalty'
    | '/admin/customers/segments'
    | '/admin/orders/$orderId'
    | '/admin/orders/live'
    | '/admin/payments/$id'
    | '/admin/petpooja/health'
    | '/admin/petpooja/logs'
    | '/admin/petpooja/queues'
    | '/admin/petpooja/stores'
    | '/admin/petpooja/webhooks'
    | '/admin/stores/$storeId'
    | '/admin/stores/create'
    | '/admin/system/apis'
    | '/admin/system/audit'
    | '/admin/system/database'
    | '/admin/system/feature-flags'
    | '/admin/system/health'
    | '/admin/system/jobs'
    | '/admin/system/logs'
    | '/admin/system/metrics'
    | '/admin/system/queues'
    | '/admin/system/redis'
    | '/admin/system/security'
    | '/admin/system/settings'
    | '/menu/product/$productId'
    | '/orders/$orderId/track'
    | '/admin/petpooja/'
    | '/admin/system/'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/force-update'
    | '/home'
    | '/maintenance'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/search'
    | '/stores'
    | '/support'
    | '/terms'
    | '/addresses/create'
    | '/admin/analytics'
    | '/admin/automation'
    | '/admin/campaigns'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/developer'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payment-health'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reconciliation'
    | '/admin/refunds'
    | '/admin/segments'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/templates'
    | '/auth/login'
    | '/auth/otp'
    | '/order-confirmation/$orderId'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/notifications'
    | '/profile/settings'
    | '/admin'
    | '/menu'
    | '/orders'
    | '/profile'
    | '/admin/campaigns/create'
    | '/admin/customers/$id'
    | '/admin/customers/analytics'
    | '/admin/customers/loyalty'
    | '/admin/customers/segments'
    | '/admin/orders/$orderId'
    | '/admin/orders/live'
    | '/admin/payments/$id'
    | '/admin/petpooja/health'
    | '/admin/petpooja/logs'
    | '/admin/petpooja/queues'
    | '/admin/petpooja/stores'
    | '/admin/petpooja/webhooks'
    | '/admin/stores/$storeId'
    | '/admin/stores/create'
    | '/admin/system/apis'
    | '/admin/system/audit'
    | '/admin/system/database'
    | '/admin/system/feature-flags'
    | '/admin/system/health'
    | '/admin/system/jobs'
    | '/admin/system/logs'
    | '/admin/system/metrics'
    | '/admin/system/queues'
    | '/admin/system/redis'
    | '/admin/system/security'
    | '/admin/system/settings'
    | '/menu/product/$productId'
    | '/orders/$orderId/track'
    | '/admin/petpooja'
    | '/admin/system'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/force-update'
    | '/home'
    | '/maintenance'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/search'
    | '/stores'
    | '/support'
    | '/terms'
    | '/addresses/create'
    | '/admin/analytics'
    | '/admin/automation'
    | '/admin/campaigns'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/developer'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payment-health'
    | '/admin/payments'
    | '/admin/petpooja'
    | '/admin/profile'
    | '/admin/reconciliation'
    | '/admin/refunds'
    | '/admin/segments'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/system'
    | '/admin/templates'
    | '/auth/login'
    | '/auth/otp'
    | '/order-confirmation/$orderId'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/favorites'
    | '/profile/notifications'
    | '/profile/settings'
    | '/admin/'
    | '/menu/'
    | '/orders/'
    | '/profile/'
    | '/admin/campaigns/create'
    | '/admin/customers/$id'
    | '/admin/customers/analytics'
    | '/admin/customers/loyalty'
    | '/admin/customers/segments'
    | '/admin/orders/$orderId'
    | '/admin/orders/live'
    | '/admin/payments/$id'
    | '/admin/petpooja/health'
    | '/admin/petpooja/logs'
    | '/admin/petpooja/queues'
    | '/admin/petpooja/stores'
    | '/admin/petpooja/webhooks'
    | '/admin/stores/$storeId'
    | '/admin/stores/create'
    | '/admin/system/apis'
    | '/admin/system/audit'
    | '/admin/system/database'
    | '/admin/system/feature-flags'
    | '/admin/system/health'
    | '/admin/system/jobs'
    | '/admin/system/logs'
    | '/admin/system/metrics'
    | '/admin/system/queues'
    | '/admin/system/redis'
    | '/admin/system/security'
    | '/admin/system/settings'
    | '/menu/product/$productId'
    | '/orders/$orderId/track'
    | '/admin/petpooja/'
    | '/admin/system/'
    | '/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForceUpdateRoute: typeof ForceUpdateRoute
  HomeRoute: typeof HomeRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OffersRoute: typeof OffersRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  StoresRoute: typeof StoresRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AddressesCreateRoute: typeof AddressesCreateRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileFavoritesRoute: typeof ProfileFavoritesRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  MenuIndexRoute: typeof MenuIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  MenuProductProductIdRoute: typeof MenuProductProductIdRoute
  OrdersOrderIdTrackRoute: typeof OrdersOrderIdTrackRoute
  OrdersOrderIdIndexRoute: typeof OrdersOrderIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-update': {
      id: '/force-update'
      path: '/force-update'
      fullPath: '/force-update'
      preLoaderRoute: typeof ForceUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/favorites': {
      id: '/profile/favorites'
      path: '/profile/favorites'
      fullPath: '/profile/favorites'
      preLoaderRoute: typeof ProfileFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/segments': {
      id: '/admin/segments'
      path: '/segments'
      fullPath: '/admin/segments'
      preLoaderRoute: typeof AdminSegmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/petpooja': {
      id: '/admin/petpooja'
      path: '/petpooja'
      fullPath: '/admin/petpooja'
      preLoaderRoute: typeof AdminPetpoojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-health': {
      id: '/admin/payment-health'
      path: '/payment-health'
      fullPath: '/admin/payment-health'
      preLoaderRoute: typeof AdminPaymentHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/developer': {
      id: '/admin/developer'
      path: '/developer'
      fullPath: '/admin/developer'
      preLoaderRoute: typeof AdminDeveloperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/addresses/create': {
      id: '/addresses/create'
      path: '/addresses/create'
      fullPath: '/addresses/create'
      preLoaderRoute: typeof AddressesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId/': {
      id: '/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof OrdersOrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/': {
      id: '/admin/system/'
      path: '/'
      fullPath: '/admin/system/'
      preLoaderRoute: typeof AdminSystemIndexRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/petpooja/': {
      id: '/admin/petpooja/'
      path: '/'
      fullPath: '/admin/petpooja/'
      preLoaderRoute: typeof AdminPetpoojaIndexRouteImport
      parentRoute: typeof AdminPetpoojaRoute
    }
    '/orders/$orderId/track': {
      id: '/orders/$orderId/track'
      path: '/orders/$orderId/track'
      fullPath: '/orders/$orderId/track'
      preLoaderRoute: typeof OrdersOrderIdTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/product/$productId': {
      id: '/menu/product/$productId'
      path: '/menu/product/$productId'
      fullPath: '/menu/product/$productId'
      preLoaderRoute: typeof MenuProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/settings': {
      id: '/admin/system/settings'
      path: '/settings'
      fullPath: '/admin/system/settings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/security': {
      id: '/admin/system/security'
      path: '/security'
      fullPath: '/admin/system/security'
      preLoaderRoute: typeof AdminSystemSecurityRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/redis': {
      id: '/admin/system/redis'
      path: '/redis'
      fullPath: '/admin/system/redis'
      preLoaderRoute: typeof AdminSystemRedisRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/queues': {
      id: '/admin/system/queues'
      path: '/queues'
      fullPath: '/admin/system/queues'
      preLoaderRoute: typeof AdminSystemQueuesRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/metrics': {
      id: '/admin/system/metrics'
      path: '/metrics'
      fullPath: '/admin/system/metrics'
      preLoaderRoute: typeof AdminSystemMetricsRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/logs': {
      id: '/admin/system/logs'
      path: '/logs'
      fullPath: '/admin/system/logs'
      preLoaderRoute: typeof AdminSystemLogsRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/jobs': {
      id: '/admin/system/jobs'
      path: '/jobs'
      fullPath: '/admin/system/jobs'
      preLoaderRoute: typeof AdminSystemJobsRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/health': {
      id: '/admin/system/health'
      path: '/health'
      fullPath: '/admin/system/health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/feature-flags': {
      id: '/admin/system/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/system/feature-flags'
      preLoaderRoute: typeof AdminSystemFeatureFlagsRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/database': {
      id: '/admin/system/database'
      path: '/database'
      fullPath: '/admin/system/database'
      preLoaderRoute: typeof AdminSystemDatabaseRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/audit': {
      id: '/admin/system/audit'
      path: '/audit'
      fullPath: '/admin/system/audit'
      preLoaderRoute: typeof AdminSystemAuditRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/system/apis': {
      id: '/admin/system/apis'
      path: '/apis'
      fullPath: '/admin/system/apis'
      preLoaderRoute: typeof AdminSystemApisRouteImport
      parentRoute: typeof AdminSystemRoute
    }
    '/admin/stores/create': {
      id: '/admin/stores/create'
      path: '/create'
      fullPath: '/admin/stores/create'
      preLoaderRoute: typeof AdminStoresCreateRouteImport
      parentRoute: typeof AdminStoresRoute
    }
    '/admin/stores/$storeId': {
      id: '/admin/stores/$storeId'
      path: '/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AdminStoresStoreIdRouteImport
      parentRoute: typeof AdminStoresRoute
    }
    '/admin/petpooja/webhooks': {
      id: '/admin/petpooja/webhooks'
      path: '/webhooks'
      fullPath: '/admin/petpooja/webhooks'
      preLoaderRoute: typeof AdminPetpoojaWebhooksRouteImport
      parentRoute: typeof AdminPetpoojaRoute
    }
    '/admin/petpooja/stores': {
      id: '/admin/petpooja/stores'
      path: '/stores'
      fullPath: '/admin/petpooja/stores'
      preLoaderRoute: typeof AdminPetpoojaStoresRouteImport
      parentRoute: typeof AdminPetpoojaRoute
    }
    '/admin/petpooja/queues': {
      id: '/admin/petpooja/queues'
      path: '/queues'
      fullPath: '/admin/petpooja/queues'
      preLoaderRoute: typeof AdminPetpoojaQueuesRouteImport
      parentRoute: typeof AdminPetpoojaRoute
    }
    '/admin/petpooja/logs': {
      id: '/admin/petpooja/logs'
      path: '/logs'
      fullPath: '/admin/petpooja/logs'
      preLoaderRoute: typeof AdminPetpoojaLogsRouteImport
      parentRoute: typeof AdminPetpoojaRoute
    }
    '/admin/petpooja/health': {
      id: '/admin/petpooja/health'
      path: '/health'
      fullPath: '/admin/petpooja/health'
      preLoaderRoute: typeof AdminPetpoojaHealthRouteImport
      parentRoute: typeof AdminPetpoojaRoute
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/admin/orders/live': {
      id: '/admin/orders/live'
      path: '/live'
      fullPath: '/admin/orders/live'
      preLoaderRoute: typeof AdminOrdersLiveRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/customers/segments': {
      id: '/admin/customers/segments'
      path: '/segments'
      fullPath: '/admin/customers/segments'
      preLoaderRoute: typeof AdminCustomersSegmentsRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/loyalty': {
      id: '/admin/customers/loyalty'
      path: '/loyalty'
      fullPath: '/admin/customers/loyalty'
      preLoaderRoute: typeof AdminCustomersLoyaltyRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/analytics': {
      id: '/admin/customers/analytics'
      path: '/analytics'
      fullPath: '/admin/customers/analytics'
      preLoaderRoute: typeof AdminCustomersAnalyticsRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/campaigns/create': {
      id: '/admin/campaigns/create'
      path: '/create'
      fullPath: '/admin/campaigns/create'
      preLoaderRoute: typeof AdminCampaignsCreateRouteImport
      parentRoute: typeof AdminCampaignsRoute
    }
  }
}

interface AdminCampaignsRouteChildren {
  AdminCampaignsCreateRoute: typeof AdminCampaignsCreateRoute
}

const AdminCampaignsRouteChildren: AdminCampaignsRouteChildren = {
  AdminCampaignsCreateRoute: AdminCampaignsCreateRoute,
}

const AdminCampaignsRouteWithChildren = AdminCampaignsRoute._addFileChildren(
  AdminCampaignsRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminCustomersAnalyticsRoute: typeof AdminCustomersAnalyticsRoute
  AdminCustomersLoyaltyRoute: typeof AdminCustomersLoyaltyRoute
  AdminCustomersSegmentsRoute: typeof AdminCustomersSegmentsRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminCustomersAnalyticsRoute: AdminCustomersAnalyticsRoute,
  AdminCustomersLoyaltyRoute: AdminCustomersLoyaltyRoute,
  AdminCustomersSegmentsRoute: AdminCustomersSegmentsRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersLiveRoute: typeof AdminOrdersLiveRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersLiveRoute: AdminOrdersLiveRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminPaymentsRouteChildren {
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
}

const AdminPaymentsRouteChildren: AdminPaymentsRouteChildren = {
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
}

const AdminPaymentsRouteWithChildren = AdminPaymentsRoute._addFileChildren(
  AdminPaymentsRouteChildren,
)

interface AdminPetpoojaRouteChildren {
  AdminPetpoojaHealthRoute: typeof AdminPetpoojaHealthRoute
  AdminPetpoojaLogsRoute: typeof AdminPetpoojaLogsRoute
  AdminPetpoojaQueuesRoute: typeof AdminPetpoojaQueuesRoute
  AdminPetpoojaStoresRoute: typeof AdminPetpoojaStoresRoute
  AdminPetpoojaWebhooksRoute: typeof AdminPetpoojaWebhooksRoute
  AdminPetpoojaIndexRoute: typeof AdminPetpoojaIndexRoute
}

const AdminPetpoojaRouteChildren: AdminPetpoojaRouteChildren = {
  AdminPetpoojaHealthRoute: AdminPetpoojaHealthRoute,
  AdminPetpoojaLogsRoute: AdminPetpoojaLogsRoute,
  AdminPetpoojaQueuesRoute: AdminPetpoojaQueuesRoute,
  AdminPetpoojaStoresRoute: AdminPetpoojaStoresRoute,
  AdminPetpoojaWebhooksRoute: AdminPetpoojaWebhooksRoute,
  AdminPetpoojaIndexRoute: AdminPetpoojaIndexRoute,
}

const AdminPetpoojaRouteWithChildren = AdminPetpoojaRoute._addFileChildren(
  AdminPetpoojaRouteChildren,
)

interface AdminStoresRouteChildren {
  AdminStoresStoreIdRoute: typeof AdminStoresStoreIdRoute
  AdminStoresCreateRoute: typeof AdminStoresCreateRoute
}

const AdminStoresRouteChildren: AdminStoresRouteChildren = {
  AdminStoresStoreIdRoute: AdminStoresStoreIdRoute,
  AdminStoresCreateRoute: AdminStoresCreateRoute,
}

const AdminStoresRouteWithChildren = AdminStoresRoute._addFileChildren(
  AdminStoresRouteChildren,
)

interface AdminSystemRouteChildren {
  AdminSystemApisRoute: typeof AdminSystemApisRoute
  AdminSystemAuditRoute: typeof AdminSystemAuditRoute
  AdminSystemDatabaseRoute: typeof AdminSystemDatabaseRoute
  AdminSystemFeatureFlagsRoute: typeof AdminSystemFeatureFlagsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminSystemJobsRoute: typeof AdminSystemJobsRoute
  AdminSystemLogsRoute: typeof AdminSystemLogsRoute
  AdminSystemMetricsRoute: typeof AdminSystemMetricsRoute
  AdminSystemQueuesRoute: typeof AdminSystemQueuesRoute
  AdminSystemRedisRoute: typeof AdminSystemRedisRoute
  AdminSystemSecurityRoute: typeof AdminSystemSecurityRoute
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
  AdminSystemIndexRoute: typeof AdminSystemIndexRoute
}

const AdminSystemRouteChildren: AdminSystemRouteChildren = {
  AdminSystemApisRoute: AdminSystemApisRoute,
  AdminSystemAuditRoute: AdminSystemAuditRoute,
  AdminSystemDatabaseRoute: AdminSystemDatabaseRoute,
  AdminSystemFeatureFlagsRoute: AdminSystemFeatureFlagsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminSystemJobsRoute: AdminSystemJobsRoute,
  AdminSystemLogsRoute: AdminSystemLogsRoute,
  AdminSystemMetricsRoute: AdminSystemMetricsRoute,
  AdminSystemQueuesRoute: AdminSystemQueuesRoute,
  AdminSystemRedisRoute: AdminSystemRedisRoute,
  AdminSystemSecurityRoute: AdminSystemSecurityRoute,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
  AdminSystemIndexRoute: AdminSystemIndexRoute,
}

const AdminSystemRouteWithChildren = AdminSystemRoute._addFileChildren(
  AdminSystemRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminCampaignsRoute: typeof AdminCampaignsRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDeveloperRoute: typeof AdminDeveloperRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentHealthRoute: typeof AdminPaymentHealthRoute
  AdminPaymentsRoute: typeof AdminPaymentsRouteWithChildren
  AdminPetpoojaRoute: typeof AdminPetpoojaRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminSegmentsRoute: typeof AdminSegmentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRouteWithChildren
  AdminSystemRoute: typeof AdminSystemRouteWithChildren
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAutomationRoute: AdminAutomationRoute,
  AdminCampaignsRoute: AdminCampaignsRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDeveloperRoute: AdminDeveloperRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentHealthRoute: AdminPaymentHealthRoute,
  AdminPaymentsRoute: AdminPaymentsRouteWithChildren,
  AdminPetpoojaRoute: AdminPetpoojaRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminSegmentsRoute: AdminSegmentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRouteWithChildren,
  AdminSystemRoute: AdminSystemRouteWithChildren,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForceUpdateRoute: ForceUpdateRoute,
  HomeRoute: HomeRoute,
  MaintenanceRoute: MaintenanceRoute,
  OffersRoute: OffersRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  StoresRoute: StoresRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AddressesCreateRoute: AddressesCreateRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileFavoritesRoute: ProfileFavoritesRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  MenuIndexRoute: MenuIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  MenuProductProductIdRoute: MenuProductProductIdRoute,
  OrdersOrderIdTrackRoute: OrdersOrderIdTrackRoute,
  OrdersOrderIdIndexRoute: OrdersOrderIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
